import { DataSteward } from './types';

export const mockStewards: DataSteward[] = [
  {
    id: '1',
    name: 'Alice Chen',
    email: 'alice@company.com',
    department: 'Chemistry R&D',
    overallHealth: 92,
    assets: [
      {
        id: 'a1',
        name: 'Compound Analytics DB',
        type: 'database',
        healthScore: 95,
        freshness: 98,
        lineageQuality: 90,
        anomalyCount: 1,
        lastUpdated: '2 hours ago',
      },
      {
        id: 'a2',
        name: 'Reaction Pipeline',
        type: 'pipeline',
        healthScore: 88,
        freshness: 85,
        lineageQuality: 92,
        anomalyCount: 3,
        lastUpdated: '4 hours ago',
      },
      {
        id: 'a3',
        name: 'Molecule Properties Dataset',
        type: 'dataset',
        healthScore: 92,
        freshness: 90,
        lineageQuality: 95,
        anomalyCount: 0,
        lastUpdated: '1 hour ago',
      },
    ],
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus@company.com',
    department: 'Process Engineering',
    overallHealth: 68,
    assets: [
      {
        id: 'b1',
        name: 'Equipment Sensor Data',
        type: 'dataset',
        healthScore: 62,
        freshness: 55,
        lineageQuality: 70,
        anomalyCount: 12,
        lastUpdated: '3 days ago',
      },
      {
        id: 'b2',
        name: 'Batch Processing Pipeline',
        type: 'pipeline',
        healthScore: 75,
        freshness: 72,
        lineageQuality: 80,
        anomalyCount: 5,
        lastUpdated: '8 hours ago',
      },
      {
        id: 'b3',
        name: 'Quality Control Metrics',
        type: 'dataset',
        healthScore: 68,
        freshness: 60,
        lineageQuality: 65,
        anomalyCount: 8,
        lastUpdated: '2 days ago',
      },
    ],
  },
  {
    id: '3',
    name: 'Sarah Williams',
    email: 'sarah@company.com',
    department: 'Analytics',
    overallHealth: 85,
    assets: [
      {
        id: 'c1',
        name: 'Sales & Performance DB',
        type: 'database',
        healthScore: 87,
        freshness: 92,
        lineageQuality: 88,
        anomalyCount: 2,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'c2',
        name: 'Customer Analytics Pipeline',
        type: 'pipeline',
        healthScore: 83,
        freshness: 80,
        lineageQuality: 85,
        anomalyCount: 4,
        lastUpdated: '5 hours ago',
      },
      {
        id: 'c3',
        name: 'Revenue Forecasting Model',
        type: 'model',
        healthScore: 85,
        freshness: 85,
        lineageQuality: 82,
        anomalyCount: 3,
        lastUpdated: '6 hours ago',
      },
    ],
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david@company.com',
    department: 'Lab Operations',
    overallHealth: 45,
    assets: [
      {
        id: 'd1',
        name: 'Lab Instrument Readings',
        type: 'dataset',
        healthScore: 38,
        freshness: 30,
        lineageQuality: 40,
        anomalyCount: 28,
        lastUpdated: '5 days ago',
      },
      {
        id: 'd2',
        name: 'Experimental Data Pipeline',
        type: 'pipeline',
        healthScore: 48,
        freshness: 45,
        lineageQuality: 50,
        anomalyCount: 15,
        lastUpdated: '4 days ago',
      },
      {
        id: 'd3',
        name: 'Sample Tracking DB',
        type: 'database',
        healthScore: 48,
        freshness: 35,
        lineageQuality: 45,
        anomalyCount: 20,
        lastUpdated: '6 days ago',
      },
    ],
  },
  {
    id: '5',
    name: 'Elena Rodriguez',
    email: 'elena@company.com',
    department: 'Product Development',
    overallHealth: 78,
    assets: [
      {
        id: 'e1',
        name: 'Product Specs Database',
        type: 'database',
        healthScore: 82,
        freshness: 88,
        lineageQuality: 80,
        anomalyCount: 3,
        lastUpdated: '2 hours ago',
      },
      {
        id: 'e2',
        name: 'Development Pipeline',
        type: 'pipeline',
        healthScore: 75,
        freshness: 70,
        lineageQuality: 78,
        anomalyCount: 6,
        lastUpdated: '12 hours ago',
      },
      {
        id: 'e3',
        name: 'Feature Tracking Dataset',
        type: 'dataset',
        healthScore: 77,
        freshness: 75,
        lineageQuality: 75,
        anomalyCount: 5,
        lastUpdated: '18 hours ago',
      },
    ],
  },
];
