import { DataSteward } from './types';

export const mockStewards: DataSteward[] = [
  {
    id: '1',
    name: 'Alice Chen',
    email: 'alice@company.com',
    department: 'Chemistry R&D',
    overallHealth: 92,
    assets: [
      {
        id: 'a1',
        name: 'Compound Analytics DB',
        type: 'database',
        healthScore: 95,
        freshness: 98,
        lineageQuality: 90,
        anomalyCount: 0,
        lastUpdated: '2 hours ago',
      },
      {
        id: 'a2',
        name: 'Reaction Pipeline',
        type: 'pipeline',
        healthScore: 88,
        freshness: 85,
        lineageQuality: 92,
        anomalyCount: 2,
        lastUpdated: '4 hours ago',
      },
      {
        id: 'a3',
        name: 'Molecule Properties Dataset',
        type: 'dataset',
        healthScore: 92,
        freshness: 90,
        lineageQuality: 95,
        anomalyCount: 0,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'a4',
        name: 'Spectroscopy Results',
        type: 'dataset',
        healthScore: 94,
        freshness: 92,
        lineageQuality: 88,
        anomalyCount: 1,
        lastUpdated: '30 min ago',
      },
      {
        id: 'a5',
        name: 'Lab Metadata',
        type: 'database',
        healthScore: 90,
        freshness: 88,
        lineageQuality: 92,
        anomalyCount: 0,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'a6',
        name: 'Synthesis Parameters',
        type: 'pipeline',
        healthScore: 91,
        freshness: 89,
        lineageQuality: 94,
        anomalyCount: 1,
        lastUpdated: '2 hours ago',
      },
      {
        id: 'a7',
        name: 'Purity Analysis',
        type: 'dataset',
        healthScore: 93,
        freshness: 91,
        lineageQuality: 91,
        anomalyCount: 0,
        lastUpdated: '45 min ago',
      },
    ],
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus@company.com',
    department: 'Process Engineering',
    overallHealth: 68,
    assets: [
      {
        id: 'b1',
        name: 'Equipment Sensor Data',
        type: 'dataset',
        healthScore: 62,
        freshness: 55,
        lineageQuality: 70,
        anomalyCount: 5,
        lastUpdated: '3 days ago',
      },
      {
        id: 'b2',
        name: 'Batch Processing Pipeline',
        type: 'pipeline',
        healthScore: 75,
        freshness: 72,
        lineageQuality: 80,
        anomalyCount: 2,
        lastUpdated: '8 hours ago',
      },
      {
        id: 'b3',
        name: 'Quality Control Metrics',
        type: 'dataset',
        healthScore: 68,
        freshness: 60,
        lineageQuality: 65,
        anomalyCount: 4,
        lastUpdated: '2 days ago',
      },
    ],
  },
  {
    id: '3',
    name: 'Sarah Williams',
    email: 'sarah@company.com',
    department: 'Analytics',
    overallHealth: 85,
    assets: [
      {
        id: 'c1',
        name: 'Sales & Performance DB',
        type: 'database',
        healthScore: 87,
        freshness: 92,
        lineageQuality: 88,
        anomalyCount: 1,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'c2',
        name: 'Customer Analytics Pipeline',
        type: 'pipeline',
        healthScore: 83,
        freshness: 80,
        lineageQuality: 85,
        anomalyCount: 2,
        lastUpdated: '5 hours ago',
      },
      {
        id: 'c3',
        name: 'Revenue Forecasting Model',
        type: 'model',
        healthScore: 85,
        freshness: 85,
        lineageQuality: 82,
        anomalyCount: 1,
        lastUpdated: '6 hours ago',
      },
      {
        id: 'c4',
        name: 'Historical Sales Data',
        type: 'dataset',
        healthScore: 88,
        freshness: 95,
        lineageQuality: 90,
        anomalyCount: 0,
        lastUpdated: '30 min ago',
      },
      {
        id: 'c5',
        name: 'Customer Segmentation',
        type: 'dataset',
        healthScore: 82,
        freshness: 78,
        lineageQuality: 80,
        anomalyCount: 3,
        lastUpdated: '12 hours ago',
      },
      {
        id: 'c6',
        name: 'Churn Prediction Model',
        type: 'model',
        healthScore: 84,
        freshness: 82,
        lineageQuality: 86,
        anomalyCount: 1,
        lastUpdated: '4 hours ago',
      },
    ],
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david@company.com',
    department: 'Lab Operations',
    overallHealth: 45,
    assets: [
      {
        id: 'd1',
        name: 'Lab Instrument Readings',
        type: 'dataset',
        healthScore: 38,
        freshness: 30,
        lineageQuality: 40,
        anomalyCount: 8,
        lastUpdated: '5 days ago',
      },
      {
        id: 'd2',
        name: 'Experimental Data Pipeline',
        type: 'pipeline',
        healthScore: 48,
        freshness: 45,
        lineageQuality: 50,
        anomalyCount: 6,
        lastUpdated: '4 days ago',
      },
      {
        id: 'd3',
        name: 'Sample Tracking DB',
        type: 'database',
        healthScore: 48,
        freshness: 35,
        lineageQuality: 45,
        anomalyCount: 7,
        lastUpdated: '6 days ago',
      },
    ],
  },
  {
    id: '5',
    name: 'Elena Rodriguez',
    email: 'elena@company.com',
    department: 'Product Development',
    overallHealth: 78,
    assets: [
      {
        id: 'e1',
        name: 'Product Specs Database',
        type: 'database',
        healthScore: 82,
        freshness: 88,
        lineageQuality: 80,
        anomalyCount: 1,
        lastUpdated: '2 hours ago',
      },
      {
        id: 'e2',
        name: 'Development Pipeline',
        type: 'pipeline',
        healthScore: 75,
        freshness: 70,
        lineageQuality: 78,
        anomalyCount: 3,
        lastUpdated: '12 hours ago',
      },
      {
        id: 'e3',
        name: 'Feature Tracking Dataset',
        type: 'dataset',
        healthScore: 77,
        freshness: 75,
        lineageQuality: 75,
        anomalyCount: 2,
        lastUpdated: '18 hours ago',
      },
      {
        id: 'e4',
        name: 'Release Timeline Data',
        type: 'dataset',
        healthScore: 80,
        freshness: 82,
        lineageQuality: 82,
        anomalyCount: 0,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'e5',
        name: 'Component Dependencies',
        type: 'database',
        healthScore: 76,
        freshness: 72,
        lineageQuality: 79,
        anomalyCount: 2,
        lastUpdated: '8 hours ago',
      },
      {
        id: 'e6',
        name: 'Test Coverage Metrics',
        type: 'dataset',
        healthScore: 79,
        freshness: 80,
        lineageQuality: 81,
        anomalyCount: 1,
        lastUpdated: '3 hours ago',
      },
      {
        id: 'e7',
        name: 'Build Performance Data',
        type: 'pipeline',
        healthScore: 74,
        freshness: 68,
        lineageQuality: 76,
        anomalyCount: 3,
        lastUpdated: '14 hours ago',
      },
      {
        id: 'e8',
        name: 'Performance Monitoring',
        type: 'dataset',
        healthScore: 81,
        freshness: 85,
        lineageQuality: 80,
        anomalyCount: 1,
        lastUpdated: '30 min ago',
      },
      {
        id: 'e9',
        name: 'User Feedback Database',
        type: 'database',
        healthScore: 75,
        freshness: 73,
        lineageQuality: 77,
        anomalyCount: 2,
        lastUpdated: '6 hours ago',
      },
      {
        id: 'e10',
        name: 'Market Analysis Data',
        type: 'dataset',
        healthScore: 80,
        freshness: 79,
        lineageQuality: 83,
        anomalyCount: 0,
        lastUpdated: '2 hours ago',
      },
    ],
  },
  {
    id: '6',
    name: 'James Wu',
    email: 'james@company.com',
    department: 'Manufacturing',
    overallHealth: 72,
    assets: [
      {
        id: 'f1',
        name: 'Production Schedule DB',
        type: 'database',
        healthScore: 76,
        freshness: 80,
        lineageQuality: 78,
        anomalyCount: 1,
        lastUpdated: '1 hour ago',
      },
      {
        id: 'f2',
        name: 'Supply Chain Pipeline',
        type: 'pipeline',
        healthScore: 70,
        freshness: 65,
        lineageQuality: 72,
        anomalyCount: 3,
        lastUpdated: '10 hours ago',
      },
      {
        id: 'f3',
        name: 'Inventory Tracking',
        type: 'dataset',
        healthScore: 72,
        freshness: 70,
        lineageQuality: 75,
        anomalyCount: 2,
        lastUpdated: '4 hours ago',
      },
      {
        id: 'f4',
        name: 'Quality Assurance Metrics',
        type: 'dataset',
        healthScore: 74,
        freshness: 72,
        lineageQuality: 76,
        anomalyCount: 2,
        lastUpdated: '5 hours ago',
      },
      {
        id: 'f5',
        name: 'Equipment Maintenance Log',
        type: 'database',
        healthScore: 68,
        freshness: 62,
        lineageQuality: 70,
        anomalyCount: 3,
        lastUpdated: '2 days ago',
      },
    ],
  },
];
